name: Update Badge on PyPI Release

on:
  workflow_run:
    workflows: ["Upload Python Package"]
    types:
      - completed

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the repository

      - name: Get PyPI Version
        id: pypi_version
        run: |
          PACKAGE_NAME=${{ secrets.PACKAGE_NAME }}
          VERSION=$(curl -s https://pypi.org/pypi/$PACKAGE_NAME/json | jq -r .info.version)
          echo "version=$VERSION" >> $GITHUB_ENV
          
      - name: Generate Badge URL
        id: generate_badge_url
        run: |
          VERSION=${{ steps.pypi_version.outputs.version }}
          BADGE_URL="https://img.shields.io/pypi/v/${VERSION}.svg"
          echo "badge_url=${BADGE_URL}" >> $GITHUB_ENV

      - name: Create Badge
        id: create_badge
        uses: emibcn/badge-action@v2.0.3
        with:
          label: 'PyPI'
          status: ${{ steps.pypi_version.outputs.version }}
          color: green
          path: 'badge.svg'  # Specify the path where the badge will be saved

      - name: Update README with Badge URL
        run: |
          BADGE_URL=${{ env.badge_url }}
          sed -i "s|image:: .*|image:: ${BADGE_URL}|g" README.rst

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.rst badge.svg
          git commit -m "Update badge for PyPI version ${{ steps.pypi_version.outputs.version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
