name: Update Badge on PyPI Release

on:
  workflow_run:
    workflows: ["Upload Python Package"]
    types:
      - completed

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get package version
      run: |
        PACKAGE_NAME="PTWordFinder"
        VERSION=$(curl -s https://pypi.org/pypi/$PACKAGE_NAME/json | jq -r .info.version)
        BADGE_URL="https://img.shields.io/pypi/v/${PACKAGE_NAME}.svg"
        README_FILE="README.rst"
        sed -i "s|!\[PyPI version\](https://img.shields.io/pypi/v/.*)|![PyPI version](${BADGE_URL})|g" $README_FILE
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.rst
        git commit -m "Update PyPI version badge"
        git push
