name: Update Badge on PyPI Release

on:
  workflow_run:
    workflows: ["Upload Python Package"]
    types:
      - completed

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Get PyPI Version (Using PyPI API)
        uses: Gr2m/pypi-version@v2.0.1  # This action fetches PyPI version
        id: pypi_version
        with:
          package_name: ${{ secrets.PTWordFinder }}  # Replace with your package name
          # api_key: ${{ secrets.PYPI_API_KEY }}  # Optional: API key for private packages

      - name: Generate Badge URL (Shields.io)
        run: |
          VERSION=${{ steps.pypi_version.outputs.version }}
          BADGE_URL="https://img.shields.io/pypi/v/$VERSION-green.svg?style=flat"
          echo "Generated Badge URL: $BADGE_URL"
        outputs:
          badge_url: ${{ steps.generate-badge.outputs.BADGE_URL }}

      - name: Download Badge Image
        uses: actions/download-artifact@v3  # Download artifact (optional)
        with:
          name: badge-image  # Artifact name (optional, adjust if needed)
          path: .  # Download location (optional, adjust if needed)

      - name: Upload Badge Image (Optional)
        uses: actions/upload-artifact@v3  # Upload artifact (optional)
        if: steps.download-badge-image.outputs.artifact_exists  # Skip if not downloaded
        with:
          name: badge-pypi-version  # Artifact name (optional, adjust if needed)
          path: badge.svg  # Upload filename (adjust as needed)

      - name: Update README.rst with Badge URL
        uses: replace-string/action@v1.1.0  # Action to replace text in file
        if: always()  # Always run, even if badge image upload is skipped
        with:
          path: README.rst  # File to modify
          pattern: '\|PyPi Badge\| image:: (.*)'  # Pattern to replace (replace with your placeholder)
          replacement: "\|PyPi Badge\| image:: ${{ steps.generate-badge.outputs.badge_url }}"
